### ISSUE TITLE
Theme breaks notification grouping

### ISSUE THREAD

**Issue by Nydragon** [catppuccin/swaync#10]
Hello there,

it seems like this theme breaks the notification grouping feature of swaync. I just opened a discussion on [ErikReider/SwayNotificationCenter](https://github.com/ErikReider/SwayNotificationCenter/discussions/427) to ask if this is an intended behaviour, but I believe this should be fixed regardless of if it is an option or not.

**Comment by isabelroses** [comment]
The grouping works for me as of the latest release. Perhaps check your config.jsob

**Comment by Nydragon** [comment]
I accidentally didn't even have the catppuccin theme activated... It works now, apologies for the noise
