### ISSUE TITLE
the do not disturb toggle displays improperly

### ISSUE THREAD

**Issue by midiidev** [catppuccin/swaync#3]
the do not disturb toggle doesn't display properly with this style for swaync.
![image](https://github.com/catppuccin/swaync/assets/101067949/9968b726-da5d-4b44-8762-0fe611e528b8)

I did notice that all of the previews don't show that toggle, so am I supposed to disable it?

**Comment by isabelroses** [comment]
Hai, thanks for bringing this to my attention since I've had the toggles disabled until now, but others may indeed want this themed so i totally forgot about this.

**Comment by isabelroses** [comment]
closed in https://github.com/catppuccin/swaync/commit/0bbbb3a62aa658493a04311cb2cb784cc60516c1
