### ISSUE TITLE
Invalid syntax and outdated command in readme

### ISSUE THREAD

**Issue by dotfrag** [catppuccin/swaync#4]
Hello and thanks for the port, it looks beautiful!

I'm using latest `swaync` version 9.0 and I see two issues.

1. Invalid CSS property (macchiato.css on line 236):

    ```css
    border: 1px s #494d64;
    ```

`s` should be `solid`, otherwise `swaync` throws `Load user CSS Error: style.css:236:16's' is not a valid color name`

2. Command to reload css in the README file is outdated (at least on my version), the latest one is:

    ```shell
    swaync-client -rs
    ```

    [source](https://github.com/ErikReider/SwayNotificationCenter#run)

**Comment by isabelroses** [comment]
thanks for caching my typo
